version: '3.6'

services:
  postgres:
    image: postgres:13-alpine
    command: ["postgres", "-c", "max_prepared_transactions=1000"]
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=pass